config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # authenticated :user do
  #   root to: 'users#show', as: :authenticated_root
  # end

  root to: "viz#index"
  resources :users, param: :slug, :only => [:show, :edit]
    patch "/users/:slug/" => "users#update"
  resources :graphs

  post 'graphs/:id/copy', to: 'graphs#copy', as: "copy_graph"

end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user
  has_many :search_categories, dependent: :destroy
  validates :title, presence: true, length: {maximum: 15}
  validates :description, length: {maximum: 200}

end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @graphs = Graph.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @graph = current_user.graphs.build

  end

  def create
    if search_categories_params.permitted? && graph_params.permitted?
      if params["search_categories"]["name"].length > 1
        @graph = current_user.graphs.build(graph_params)
        @user = current_user
        insert_categories
        if @graph.save
          redirect_to graph_path(@graph)
        else
          flash[:error] = "A graphs title must be between 1 and 200 characters."
          redirect_back fallback_location: new_graph_path
        end
      else
        flash[:error] = "Search categories cannot be empty"
        redirect_back fallback_location: new_graph_path
      end
    else
      flash[:error] = "Not permitted action"
      redirect_back fallback_location: new_graph_path
    end
  end

  def destroy
    graph_id = params[:id]
    graph = Graph.find_by_id(graph_id)
    graph.destroy
    redirect_back(fallback_location: root_path)
  end

  def show
    graph_id = params[:id]
    @graph = Graph.find_by_id(graph_id)
    category_restricts = @graph.search_categories.map { |category|
      category = 'category = ' + "'#{category.name}'"
    }
    category_restricts = category_restricts.join(" OR ")
    conditions = category_restricts
    @listing = JobListing.where(conditions)
    if @listing.empty?
      flash[:error] = "Sorry, there are no relevant results."
    end
    # then use association to display top 10 cities by categories

  end

  def copy
    graph_id = params[:id]
    @graph = Graph.find_by_id(graph_id)
    if @graph.nil?
      flash[:error] = "Sorry, this graph does not exist."
    else
      @graph_copy = Graph.new
      @graph_copy[:title] = @graph.title
      @graph_copy[:x_axis] = @graph.x_axis
      @graph_copy[:graph_type] = @graph.graph_type
      @graph_copy[:user_id] = current_user.id
      @graph_copy[:description] = @graph.description
      if @graph_copy.save
        redirect_to user_path(current_user)
      else
        flash[:error] = "Cant save a copy of this"
        redirect_to graph_path(@graph)
      end
    end

  end

  def edit
    graph_id = params[:id]
    @graph = Graph.find_by_id(graph_id)
  end

  def update
    if search_categories_params.permitted? && graph_params.permitted?
      graph_id = params[:id]
      @graph = Graph.find_by_id(graph_id)
      if params["search_categories"]["name"].length > 1
        @graph.update(graph_params)
        @graph.search_categories.destroy_all
        insert_categories
        if @graph.valid?

          redirect_to graph_path(@graph)
        else
          flash[:error] = "A graphs title must be between 1 and 15 characters."
          redirect_back fallback_location: edit_graph_path
        end
      else
        flash[:error] = "Search categories cannot be empty"
        redirect_back fallback_location: edit_graph_path
      end
    else
      flash[:error] = "Not permitted action"
      redirect_back fallback_location: edit_graph_path
    end
  end

  private

  def insert_categories
    @scParams = params["search_categories"]["name"]
    if @scParams.include?('All Categories')
      JobCategory.all[0..-2].each do |category|
        new_category = SearchCategory.new
        new_category[:name] = category[:name]
        @graph.search_categories << new_category
      end
    else
      @scParams.each do | category|
        if !category.empty?
          new_category = SearchCategory.new
          new_category[:name] = category
          @graph.search_categories << new_category
        end
      end
    end
  end

  def graph_params
    params.require(:graph).permit(:title, :x_axis, :graph_type, :description)
    end

  def search_categories_params
      params.require(:search_categories).permit(:name)
  end

end

app/helpers/graphs_helper.rb
module GraphsHelper

  def render_bar_graph
    bar_chart @listing.group(:category).group(@graph.x_axis).count, download: 'bar_chart',
    library: {options:{
                legend:{
                  labels:{
                    fontColor: "red"
                  }
                }
              }
            },
    xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings", height: "100%"
  end

  def render_pie_graph
    pie_chart @listing.group(@graph.x_axis).count,download: 'pie_chart',
    xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings", height: "100%"
  end

  def render_line_graph
    line_chart @listing.group(:category).group(@graph.x_axis).count, download: 'line_chart',
    xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings", height: "100%"
  end

  def render_column_graph
    column_chart @listing.group(:category).group(@graph.x_axis).count, download: 'column_chart',
    xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings", height: "100%"
  end

  def filter_listing_by_top_cities
    #grabbing array of cities
    cities = @listing.top(:city,11)
    i = 1
    graph_id = params[:id]
    @graph = Graph.find_by_id(graph_id)
    category_restricts = @graph.search_categories.map { |category|
      category = 'category = ' + "'#{category.name}'"
    }
    category_restricts = category_restricts.join(" OR ")
    filtered_association =  JobListing.where("city = '#{cities.keys[0]}'
            AND city <> 'City N/A' AND (#{category_restricts}) ")
    (cities.length-1).times do
      new_record = JobListing.where("city = '#{cities.keys[i]}'
            AND city <> 'City N/A' AND (#{category_restricts}) ")
      filtered_association = filtered_association.or(new_record)
      i = i + 1
    end
    @listing = filtered_association
  end
end

app/views/graphs/index.html.erb
<div class="container">
  <div class="row wht-bk blk-font">
    <div class="col s12">
      <h4>ALL<span class="text-prim-color"> GRAPHS</span></h4>
      <hr>
      <% @graphs.each do |graph| %>
      <div class="row row-bottom">
        <div class="col s12">
          <h5><%= graph.title.upcase %></h5>
        </div>
      </div>
      <div class="row">
        <%= render partial: "shared/graph_show_content", locals: {graph: graph}%>
      </div>
      <hr>
      <% end %>
      <div class="paginate-graphs">
        <%= paginate @graphs %>
        <div class="pagination_page_info">
          <%= page_entries_info @graphs %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/graphs/new.html.erb
<div class="error">
  <% flash.each do |name, msg| %>
  <%= msg %>
  <% end %>
</div>

<div class="container">
  <div class="row wht-bk blk-font row-margin">
    <div class="col s12">
      <h3>CREATE A<span class="text-prim-color"> GRAPH</span></h3>
      <hr>
      <%= form_for @graph do |f| %>
      <div class="graph-title-input">
        <p><b>Title: </b></p>
        <%= f.text_field :title, placeholder: "Input Title", :maxlength => 15, class: "graph-input-inline", autofocus: true %>
      </div>
      <div class="graph-description-input">
      <p><b>Description: </b></p>
        <%= f.text_area :description, placeholder: "Input Description", :maxlength => 200, class: "graph-input-description" %>
      </div>
      <p><b>Job Categories</b></p>
      <div class="check-boxes">
        <%= collection_check_boxes(:search_categories, :name, JobCategory.all, :name, :name) %>
      </div>
      <p><b>Search Criteria: </b></p>
      <div class="search-dropdown" >
        <%= f.select(:x_axis, [['By Job Category', 'category'], ['Top 10 Company Cities', 'city'], ['By Post Date', 'post_date'],
          ['By Company Country', 'country'] ]) %>
        </div>
        <p><b>Graph Type: </b></p>
        <div class="graph-dropdown">
          <%= f.select(:graph_type, [['Bar Graph','bar'], ['Pie Chart','pie'], ['Line Graph','line'], ['Column Graph','column']]) %>
        </div><br>
          <%= f.submit "Create Graph", class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/graphs/show.html.erb
<div class="left_nav_form">
  <% if current_user.nil? == true %>
  <!-- render as plain txt on left nav, display author, title, categories -->
    <%= render "partial/graph_info" %>
    <div class="description_container row">
        <h5>Description:</h5>
        <p class="col s10 description" id="plain_desc"> <%= @graph.description %> </p>
    </div>
  <% elsif current_user.id == @graph.user.id %>
    <!-- Render editable form for creator = logged user -->
    <%= form_for @graph  do |f|  %>
      <%= f.text_field :title, placeholder: "Title", maxlength: "15" %><br>
      <span class="pink-font str">Job Categories:</span><br><%= collection_check_boxes(:search_categories, :name, JobCategory.all, :name, :name, id: "wht-font") %><br><br>
      <div class="pink-font str">Group Job Categories By:</div> <%= f.select(:x_axis, [['Job Category', 'category'], ['Top 10 Company Cities', 'city'], ['Post Date (Weekly)', 'post_date'],
      ['Company Country', 'country']] ) %><br>
      <div class="pink-font str">Graph Type:</div> <%= f.select(:graph_type, [['Bar Graph','bar'], ['Pie Graph','pie'], ['Line Graph','line'], ['Column Graph','column']]) %><br>
      <div class="description_container row">
        <h5>Description:</h5>
        <p class="toggle col s10 " id="plain_desc"><%= @graph.description %> </p>
        <p class="toggle hidden input-field description col s10">
          <%= f.text_area :description, placeholder: "Graph Description Goes Here",
              class: "materialize-textarea" , autofocus: true, maxlength: "200" %>
        </p>
        <a type="button" class="tgl_desc_btn btn-floating right col s2">
          <i class="medium material-icons">mode_edit</i>
        </a>
      </div>
      <%= f.submit "Update", class: "btn" %>
      <% end %>
  <% else %>
      <!-- else logged in used is diff from graph creator,enable save collection to logged in user to their own Profile -->
        <%= render "partial/graph_info" %><br>
        <div class="description_container row">
            <h5>Description:</h5>
            <p class="col s10 description" id="plain_desc"> <%= @graph.description %> </p>
        </div>
        <%= form_for @graph, url: copy_graph_path, method: "post" do |f|   %>
        <%= f.submit "Copy to Profile", class: "btn" %>
        <% end %>
  <% end %>
</div>

<div class="graph_container">
  <div class="error">
    <h3><% flash.each do |name, msg| %>
      <%= msg %><h3>
        <% end %>
  </div>
  <% if !@listing.empty?  %>
      <div class="graph">
        <% graph_h = "100%" %>
  <% if @graph.graph_type == 'bar' %>
          <% if @graph.x_axis == 'post_date' %>
            <%= bar_chart @listing.group(:category).group_by_week(@graph.x_axis).count, height: "#{graph_h}",
                xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings"%>
          <% elsif @graph.x_axis == 'city' %>
            <% filter_listing_by_top_cities %>
            <%= render_bar_graph %>
          <% else %>
            <%= render_bar_graph %>
          <% end %>

  <% elsif @graph.graph_type == 'line' %>
        <% if @graph.x_axis == 'city' %>
          <% filter_listing_by_top_cities %>
          <%= render_line_graph %>
        <% elsif @graph.x_axis == 'post_date' %>
          <%= line_chart @listing.group(:category).group_by_week(@graph.x_axis).count, height: "#{graph_h}",
              xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings"%>
        <% else %>
          <%= render_line_graph %>
        <% end %>
  <% elsif @graph.graph_type == 'pie' %>
        <% if @graph.x_axis == 'post_date' %>
          <%= pie_chart @listing.group_by_week(@graph.x_axis).count, height: "#{graph_h}",
              xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings"%>
        <% elsif @graph.x_axis == 'city' %>
          <% filter_listing_by_top_cities %>
          <%= render_pie_graph %>
        <% else %>
          <%= render_pie_graph %>
        <% end %>
  <% elsif @graph.graph_type == 'column' %>
        <% if @graph.x_axis =='post_date' %>
          <%= column_chart @listing.group(:category).group_by_week(@graph.x_axis).count, height: "#{graph_h}",
              xtitle: @graph.x_axis.upcase, ytitle: "Number of Job Listings"%>
        <% elsif @graph.x_axis == 'city' %>
          <% filter_listing_by_top_cities %>
          <%= render_column_graph %>
        <% else %>
          <%= render_column_graph %>
        <% end %>
  <% end %>
      <!-- ends else/if for different graph_type -->
    <% end %>
    <!-- end for @listing is empty -->
  </div>
  <div class="hidden_block">
  </div>
</div>
<!-- end of graph container -->