config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # authenticated :user do
  #   root to: 'users#show', as: :authenticated_root
  # end

  root to: "viz#index"
  resources :users, param: :slug, :only => [:show, :edit]
    patch "/users/:slug/" => "users#update"
  resources :graphs

  post 'graphs/:id/copy', to: 'graphs#copy', as: "copy_graph"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :graphs, dependent: :destroy;

  # Handles the URLS
  include FriendlyId
  friendly_id :first_name_and_last_name, use: [:finders, :slugged]

  def first_name_and_last_name
  "#{first_name}-#{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user)
  end

  def show
    @user = User.friendly.find(params[:slug])
    @graphs = @user.graphs.order(created_at: :desc).page(params[:page]).per(5)

  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :city, :email, :password, :image)
  end

  def user_update_params
    params.require(:user).permit(:first_name, :last_name, :city, :email, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <br>
      <%= form_for @user do |f| %>
        <%= render partial: "layouts/user_forms", locals: { f: f } %>
      <%= f.submit "Create Account", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <!-- BEG row for entire page -->
  <div class="row row-user-page">
    <!-- BEG left column for profile -->
    <div class="col m3 hide-on-med-and-down col-prof" id="leftCol">
      <!-- BEG container for ALL profile content -->
      <div class="outside-container-prof">
        <div class="inside-container-prof">
          <!-- BEGIN row for image container -->
          <div class="background-photo">
            <div class="row">
              <div class="col m8 offset-m2">
                <% if @user.image.empty? %>
                <%= image_tag(asset_path('default_profile_image.jpg'), class: "circle") %>
                <% else %>
                <%= image_tag(@user.image, class: "circle circle-prof") %>
                <% end %>
              </div>
              <!-- BEGIN row for name -->
              <div class="center-align">
                <h5 class="prof-title"><%= @user.first_name.upcase %> <%= @user.last_name.upcase %></h5>
              </div>
              <!-- END row for name -->
              <!-- BEG row for edit button -->
              <div class="prof-btn-edit">
                <% if @user == current_user %>
                <%= link_to(edit_user_registration_path, class: "btn-floating btn-medium") do  %>
                <i class="medium material-icons">mode_edit</i>
                <% end %>
                <% end %>
              </div>
              <!-- END row for edit button -->
            </div>
          </div>
          <!-- END row for image container -->
          <!-- BEG row for profile text contenent -->
          <div class="center-align">
            <h5>Profile Information</h5>
            <hr>
            <p><%= @user.city %><br>
              <b>Member Since: </b><%= @user.created_at.strftime("%B").to_s + " " + @user.created_at.year.to_s %></p>
            </div>
            <!-- END row for profile text contenent -->
          </div>
        </div>
        <!-- END container for ALL profile content -->
      </div>
      <!-- END column for left profile -->
      <!-- BEG column for right data -->
      <div class="col m12 l9" id="rightCol">
        <!-- BEG container for ALL profile content -->
        <div class="outside-container-data">
          <div class="inside-container-data">
            <div>
              <h4><%= @user.first_name.upcase %> <%= @user.last_name.upcase %>'S<span class="text-prim-color"> GRAPHS</span></h4>
              <hr>
            </div>
            <div class="wht-bk blk-font">
              <% @graphs.each do |graph| %>
              <div class="row">
                <div class="col s12">
                  <h5 class="prof-title-graph"><%= graph.title.upcase %></h5>
                  <!-- BEG row for edit button -->
                  <% if graph.user == current_user %>
                  <div class="user-graph-btn">
                    <%= button_to(graph_path(graph.id), method: 'get', class: "btn-floating btn-medium btn-blk btn-inline") do  %>
                    <i class="medium material-icons">mode_edit</i>
                    <% end %>
                    <%= button_to(graph_path(graph.id), method: 'delete', data:   {:confirm => "Are you sure you want to delete the #{graph.title} graph?"}, :method => :delete, class: "btn-floating btn-medium btn-blk btn-inline") do  %>
                    <i class="medium material-icons">delete</i>
                    <% end %>
                    <% end %>
                  </div>
                  <!-- END row for edit button -->
                </div>
                <div class="row">
                  <%= render partial: "shared/graph_show_content", locals: {graph: graph}%>
                </div>
                <hr>
              </div>
              <% end %>
              <div class="paginate-graphs">
                <%= paginate @graphs %>
                <div class="pagination_page_info">
                  <%= page_entries_info @graphs %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- END container for ALL profile content -->
      </div>
      <!-- END column for right data -->
    </div>
    <!-- END row for entire page -->
  </div>