config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # authenticated :user do
  #   root to: 'users#show', as: :authenticated_root
  # end

  root to: "viz#index"
  resources :users, param: :slug, :only => [:show, :edit]
    patch "/users/:slug/" => "users#update"
  resources :graphs

  post 'graphs/:id/copy', to: 'graphs#copy', as: "copy_graph"

end

app/views/layouts/_def_back_end.html.erb
<h5 class="text-prim-color">BACK END WEB DEVELOPER</h5>
<p>Back-end developers, or at least back-end development, are required to create a dynamic site. A dynamic site is a site that's constantly changing and updated in real-time. Most sites are dynamic sites, as opposed to static sites.  Facebook, Google Maps and this blog are all considered dynamic sites. Blogs are dynamic sites, since their content is constantly changing and updating. A dynamic site requires a database to work properly.  All  information, like user profiles or images they've uploaded, or blog posts, are stored in the database. Web developers work with programming languages like PHP or .Net, since they need to work with something the database understands. The code they write communicates with the server and then tells the browser what to use from the database.
</p>

app/views/layouts/_def_front_end.html.erb
<h5 class="text-prim-color">FRONT END WEB DEVELOPER</h5>
<p>The front-end is everything involved with what the user sees, including design and some languages like HTML and CSS. There are a lot of different jobs associated with the front-end. Keep in mind that a lot of these titles are subjective, and while front-end developer may mean something at one company, it can mean something completely different at another company. A common front-end job title is "web designer." A web designer, you guessed it, designs websites. The job title of web designer is pretty broad, though. A web designer could just be someone who designs the sites in a program like Photoshop or Fireworks and will never touch the code. But in another location, a web designer could do all the design comps in Photoshop, and then be responsible for creating all the HTML and CSS (and sometimes even JavaScript) to go along with it.
</p>

app/views/layouts/_def_management.html.erb
<h5 class="text-prim-color">MANAGER</h5>
<p>In support of these responsibilities, the Web Manager should demonstrate a high degree of competence, knowledge and expertise in the following areas: Web operations, including publishing, analytics, technical monitoring, etc. Online development, including planning, design, content, technology & publicity.
</p>

app/views/layouts/_def_marketing.html.erb
<h5 class="text-prim-color">MARKETING</h5>
<p>The marketing strategist plays a key role in the long-term success of your website. As such, the marketing strategist plays an important role in maximizing your website's ROI. 2) UX Designer. An Agile web design process always begins with the team's involvement in scoping and prioritizing elements of the project.
</p>

app/views/layouts/_def_prod_man.html.erb
<h5 class="text-prim-color">PRODUCT MANAGER</h5>
<p>The Product Manager (or PM) is responsible for the strategy, roadmap, and feature definition of a product or product line. The role involves working with cross-functional teams and may include marketing, forecasting, and profit and loss (P&L) responsibilities.
</p>

app/views/layouts/_def_ux.html.erb
<h5 class="text-prim-color">UX DESIGNER</h5>
<p>A UX researcher is the champion of a user's needs. The goal of a researcher is to answer the twin questions of “Who are our users?” and “What do our users want?” Typically, this role entails interviewing users, researching market data, and gathering findings. Design is a process of constant iteration.
</p>

app/views/layouts/_prof_button_header.html.erb
<div class="inside-container-prof">
  <!-- BEGIN row for image container -->
  <div class="background-photo">
    <div class="row prof-button-row valign-wrapper">
      <div class="col s4">
        <%= image_tag(user.image, class: "circle circle-mobile valign-wrapper") %>
      </div>
      <!-- BEGIN row for name -->
      <div class="col s8 test">
        <h5 class="prof-title"><%= user.first_name.upcase %> <%= user.last_name.upcase %></h5>
        <!-- BEG row for edit button -->
        <div class="prof-btn-edit">
          <% if user == current_user %>
          <%= link_to edit_user_registration_path, class: "btn-floating btn-medium" do  %>
          <i class="medium material-icons">mode_edit</i>
          <% end %>
          <% end %>
        </div>
        <!-- END row for edit button -->
      </div>
      <!-- END row for name -->
    </div>
  </div>
  <!-- END row for image container -->
</div>

app/views/layouts/_user_forms.html.erb
<h5>Become a member of Viz!</h5>
<div>
  <%= f.label :first_name, "First Name"%>
  <%= f.text_field :first_name%>
</div>
<div>
  <%= f.label :last_name, "Last Name"%>
  <%= f.text_field :last_name %>
</div>
<div>
  <%= f.label :city, "City"%>
  <%= f.text_field :city %>
</div>
<div>
  <%= f.label :email, "Email"%>
  <%= f.email_field :email %>
</div>
<div>
  <%= f.label :image, "Profile Picture" %>
  <%= f.url_field :image %>
</div>
<div>
  <%= f.label :password, "Password"%>
  <%= f.password_field :password %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viz</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Oswald|Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper text-white">
        <%= link_to "VIZ.DATA", root_path, class: "brand-logo" %>
        <a href="" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Graphs", graphs_path %></li>
          <% if current_user %>
          <li><%= link_to "Create", new_graph_path(current_user) %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">

          <% if current_user %>
          <li><%= render partial: "layouts/prof_button_header"%></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Graphs", graphs_path %></li>
          <li><%= link_to "Create", new_graph_path(current_user) %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Graphs", graphs_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <!-- This tag allows you to change to the css of a specific page -->
  <%= stylesheet_link_tag %>
  <%= yield(:head) %>

  <div class="col s8">
    <% flash.each do |name, msg| %>
    <div id='toast-container'>
      <%= javascript_tag "Materialize.toast('#{msg}', 4000)" %>
    </div>
    <% end %>
  </div>

  <%= yield %>


</body>
</html>